[package]
name = "fsum"
version = "0.1.0"
authors = ["Hrvoje Niksic <hniksic@gmail.com>"]

[dependencies]
rayon = "0.5.0"

[dependencies.concurrent-hashmap]
version = "0.2.1"
default-features = false
