[package]
name = "fsum"
version = "0.1.0"
authors = ["Hrvoje Niksic <hniksic@gmail.com>"]

[dependencies]
rayon = "1.3.0"

[dependencies.concurrent-hashmap]
version = "0.2.2"
default-features = false
